POST http://localhost:8080/items HTTP/1.1
content-type: application/json

[
    {
        "description": "Bread",
        "price": 2.80
    },
        {
        "description": "Milk",
        "price": 1.99
    },
    {
        "description": "Eggs",
        "price": 0.89
    },
    {
        "description": "Nutella",
        "price": 8.88
    },
    {
        "description": "Tomatoes",
        "price": 1.99
    },
    {
        "description": "Onions",
        "price": 2.39
    },
    {
        "description": "Beers",
        "price": 12.99
    }
    
]