POST http://localhost:8080/items HTTP/1.1
content-type: application/json

[
    {
        "description": "Bread",
        "price": 2.80,
        "imageFile": "bread.png"
    },
        {
        "description": "Milk",
        "price": 1.99,
        "imageFile": "milk.png"
    },
    {
        "description": "Eggs",
        "price": 0.89,
        "imageFile": "eggs.png"
    },
    {
        "description": "Tomatoes",
        "price": 1.99,
        "imageFile": "tomato.png"
    },
    {
        "description": "Beers",
        "price": 12.99,
        "imageFile": "beer.png"
    },
    {
        "description": "Butter",
        "price": 12.99,
        "imageFile": "butter.png"
    },
    {
        "description": "Lettuce",
        "price": 12.99,
        "imageFile": "lettuce.png"
    },
    {
        "description": "Liquid Soap",
        "price": 12.99,
        "imageFile": "liquid-soap.png"
    },
    {
        "description": "Olive Oil",
        "price": 12.99,
        "imageFile": "olive-oil.png"
    },
    {
        "description": "Potato Chips",
        "price": 12.99,
        "imageFile": "potato-chips.png"
    }
    
]